### ISSUE TITLE
Error with make GDS when running IO Placement.

### ISSUE THREAD

**Issue by BenAtUvu** [TinyTapeout/tt03-submission-template#2]
(https://github.com/BenAtUvu/tt03-ComboLock/actions/runs/4507289039/jobs/7934932859#step:8:62)

error message reads:
Error: : during executing: "openroad -exit -no_init -python /openlane/scripts/odbpy/io_place.py --config /work/src/pin_order.cfg --hor-layer met3 --ver-layer met2 --ver-width-mult 2 --hor-width-mult 2 --hor-extension 0 --ver-extension 0 --length 2 --unmatched-error --input-lef /work/runs/wokwi/tmp/merged.nom.lef --output-def /work/runs/wokwi/tmp/floorplan/4-io.def --output /work/runs/wokwi/tmp/floorplan/4-io.odb /work/runs/wokwi/tmp/floorplan/3-initial_fp.odb |& tee /dev/null /work/runs/wokwi/logs/floorplan/4-place_io.log"

**Comment by mattvenn** [comment]
you must follow the module ports definition given in the template.
https://github.com/BenAtUvu/tt03-ComboLock/blob/main/src/combolock.v#L2

clue in the logs
https://github.com/BenAtUvu/tt03-ComboLock/actions/runs/4507289039/jobs/7934932859#step:8:48

good idea to check this: https://tinytapeout.com/hdl/important/
