### ISSUE TITLE
Fix end quote on title

### ISSUE THREAD

**Issue by mattvenn** [TinyTapeout/tt03-submission-template#5]
@robbertvanginkel - pls fix the non-matched end quote here:

https://github.com/robbertvanginkel/tt03-hamming74/blob/2260c198b9cd8159b224e12fc017a5bc32ece6c7/info.yaml#L23

**Comment by robbertvanginkel** [comment]
Oops, should be fixed in https://github.com/robbertvanginkel/tt03-hamming74/commit/686bf08029d616e6336e1881a21927cadebebe05.
